version: "3"

services:
  nextcloud:
    image: nextcloud
    ports:
      - 7070:80
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=HCNGqAW69U
      - NEXTCLOUD_ADMIN_PASSWORD=UvgnAVNQKN
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
